import type { CropProfile } from '../../../types/domain';

export const cropCatalog: CropProfile[] = [
  {
    id: 'milho',
    name: 'Milho',
    description: 'Cultura anual com alta exigência hídrica no florescimento.',
    soil: {
      textures: ['medio', 'argiloso'],
      drainage: ['bom', 'medio'],
      irrigationRecommended: true,
    },
    stages: [
      {
        id: 'estabelecimento',
        name: 'Estabelecimento',
        durationShare: 0.2,
        weight: 0.8,
        thresholds: {
          tempMinIdeal: 18,
          tempMaxIdeal: 30,
          tempMinCritical: 12,
          tempMaxCritical: 35,
          precipMinPerDay: 2.5,
          precipMaxPerDay: 12,
          windMax: 16,
          humidityMin: 45,
          humidityMax: 85,
          pestTempMin: 20,
          pestTempMax: 30,
          pestHumidityMin: 70,
        },
      },
      {
        id: 'vegetativo',
        name: 'Desenvolvimento vegetativo',
        durationShare: 0.4,
        weight: 1,
        thresholds: {
          tempMinIdeal: 20,
          tempMaxIdeal: 32,
          tempMinCritical: 14,
          tempMaxCritical: 36,
          precipMinPerDay: 3,
          precipMaxPerDay: 12,
          windMax: 16,
          humidityMin: 45,
          humidityMax: 85,
          pestTempMin: 20,
          pestTempMax: 32,
          pestHumidityMin: 70,
        },
      },
      {
        id: 'florescimento',
        name: 'Florescimento',
        durationShare: 0.2,
        weight: 1.3,
        thresholds: {
          tempMinIdeal: 20,
          tempMaxIdeal: 30,
          tempMinCritical: 15,
          tempMaxCritical: 35,
          precipMinPerDay: 3.5,
          precipMaxPerDay: 10,
          windMax: 14,
          humidityMin: 50,
          humidityMax: 85,
          pestTempMin: 20,
          pestTempMax: 30,
          pestHumidityMin: 75,
        },
      },
      {
        id: 'enchimento',
        name: 'Enchimento de grãos',
        durationShare: 0.2,
        weight: 1,
        thresholds: {
          tempMinIdeal: 18,
          tempMaxIdeal: 30,
          tempMinCritical: 12,
          tempMaxCritical: 34,
          precipMinPerDay: 2.5,
          precipMaxPerDay: 10,
          windMax: 16,
          humidityMin: 45,
          humidityMax: 85,
          pestTempMin: 20,
          pestTempMax: 30,
          pestHumidityMin: 70,
        },
      },
    ],
    yieldModel: {
      baselineYield: 5.5,
      minYield: 2.5,
      maxYield: 9,
      sensitivity: 0.7,
      riskWeights: {
        water_stress: 0.3,
        water_excess: 0.15,
        heat_stress: 0.2,
        cold_stress: 0.1,
        wind_risk: 0.05,
        pest_disease: 0.1,
        soil_suitability: 0.1,
      },
    },
  },
  {
    id: 'soja',
    name: 'Soja',
    description: 'Cultura anual sensível a estresse hídrico em florescimento.',
    soil: {
      textures: ['medio', 'argiloso'],
      drainage: ['bom', 'medio'],
      irrigationRecommended: false,
    },
    stages: [
      {
        id: 'estabelecimento',
        name: 'Estabelecimento',
        durationShare: 0.2,
        weight: 0.9,
        thresholds: {
          tempMinIdeal: 20,
          tempMaxIdeal: 30,
          tempMinCritical: 12,
          tempMaxCritical: 35,
          precipMinPerDay: 2.5,
          precipMaxPerDay: 10,
          windMax: 16,
          humidityMin: 45,
          humidityMax: 85,
          pestTempMin: 20,
          pestTempMax: 30,
          pestHumidityMin: 70,
        },
      },
      {
        id: 'vegetativo',
        name: 'Desenvolvimento vegetativo',
        durationShare: 0.35,
        weight: 1,
        thresholds: {
          tempMinIdeal: 20,
          tempMaxIdeal: 32,
          tempMinCritical: 12,
          tempMaxCritical: 35,
          precipMinPerDay: 2.8,
          precipMaxPerDay: 10,
          windMax: 16,
          humidityMin: 45,
          humidityMax: 85,
          pestTempMin: 20,
          pestTempMax: 32,
          pestHumidityMin: 70,
        },
      },
      {
        id: 'florescimento',
        name: 'Florescimento',
        durationShare: 0.25,
        weight: 1.3,
        thresholds: {
          tempMinIdeal: 20,
          tempMaxIdeal: 30,
          tempMinCritical: 14,
          tempMaxCritical: 35,
          precipMinPerDay: 3,
          precipMaxPerDay: 9,
          windMax: 14,
          humidityMin: 50,
          humidityMax: 85,
          pestTempMin: 20,
          pestTempMax: 30,
          pestHumidityMin: 75,
        },
      },
      {
        id: 'enchimento',
        name: 'Enchimento de grãos',
        durationShare: 0.2,
        weight: 1.1,
        thresholds: {
          tempMinIdeal: 18,
          tempMaxIdeal: 30,
          tempMinCritical: 12,
          tempMaxCritical: 34,
          precipMinPerDay: 2.5,
          precipMaxPerDay: 9,
          windMax: 16,
          humidityMin: 45,
          humidityMax: 85,
          pestTempMin: 20,
          pestTempMax: 30,
          pestHumidityMin: 70,
        },
      },
    ],
    yieldModel: {
      baselineYield: 3.2,
      minYield: 1.5,
      maxYield: 5,
      sensitivity: 0.65,
      riskWeights: {
        water_stress: 0.35,
        water_excess: 0.15,
        heat_stress: 0.2,
        cold_stress: 0.08,
        wind_risk: 0.05,
        pest_disease: 0.1,
        soil_suitability: 0.07,
      },
    },
  },
  {
    id: 'cafe',
    name: 'Café',
    description: 'Cultura perene com forte sensibilidade térmica na florada.',
    soil: {
      textures: ['medio', 'argiloso'],
      drainage: ['bom', 'medio'],
      irrigationRecommended: true,
    },
    stages: [
      {
        id: 'floracao',
        name: 'Floração',
        durationShare: 0.3,
        weight: 1.2,
        thresholds: {
          tempMinIdeal: 18,
          tempMaxIdeal: 26,
          tempMinCritical: 10,
          tempMaxCritical: 30,
          precipMinPerDay: 2,
          precipMaxPerDay: 8,
          windMax: 14,
          humidityMin: 50,
          humidityMax: 85,
          pestTempMin: 18,
          pestTempMax: 28,
          pestHumidityMin: 75,
        },
      },
      {
        id: 'frutificacao',
        name: 'Frutificação',
        durationShare: 0.4,
        weight: 1.1,
        thresholds: {
          tempMinIdeal: 18,
          tempMaxIdeal: 28,
          tempMinCritical: 10,
          tempMaxCritical: 32,
          precipMinPerDay: 2,
          precipMaxPerDay: 8,
          windMax: 14,
          humidityMin: 50,
          humidityMax: 85,
          pestTempMin: 18,
          pestTempMax: 28,
          pestHumidityMin: 75,
        },
      },
      {
        id: 'maturacao',
        name: 'Maturação',
        durationShare: 0.3,
        weight: 1,
        thresholds: {
          tempMinIdeal: 18,
          tempMaxIdeal: 28,
          tempMinCritical: 10,
          tempMaxCritical: 32,
          precipMinPerDay: 1.8,
          precipMaxPerDay: 7,
          windMax: 14,
          humidityMin: 50,
          humidityMax: 85,
          pestTempMin: 18,
          pestTempMax: 28,
          pestHumidityMin: 75,
        },
      },
    ],
    yieldModel: {
      baselineYield: 2,
      minYield: 1,
      maxYield: 3.6,
      sensitivity: 0.6,
      riskWeights: {
        water_stress: 0.25,
        water_excess: 0.15,
        heat_stress: 0.2,
        cold_stress: 0.15,
        wind_risk: 0.05,
        pest_disease: 0.1,
        soil_suitability: 0.1,
      },
    },
  },
];
