import type { CropProfile } from '../../../types/domain';

export const cropCatalog: CropProfile[] = [
  {
    id: 'milho',
    name: 'Milho 1ª safra',
    description: 'Milho de sequeiro com análise agroclimática baseada no ZARC da 1ª safra.',
    cycleDays: 120,
    cycleModel: {
      method: 'thermal-time',
      baseTempC: 10,
      referenceTempC: 22.5,
      minCycleDays: 105,
      maxCycleDays: 150,
    },
    soil: {
      textures: ['arenoso', 'medio', 'argiloso'],
      drainage: ['bom', 'medio', 'ruim'],
    },
    stages: [
      {
        id: 'fase_1',
        name: 'Germinação e emergência',
        durationShare: 0.125,
        weight: 1,
        thresholds: {
          tempAvgMinIdeal: 15,
          tempAvgMinCritical: 10,
          tempMinIdeal: 10,
          tempMinCritical: 2,
          precipMinPerDay: 4.17,
        },
      },
      {
        id: 'fase_2',
        name: 'Crescimento e desenvolvimento',
        durationShare: 0.375,
        weight: 0.85,
        thresholds: {
          tempAvgMinIdeal: 15,
          tempAvgMinCritical: 10,
          tempMinIdeal: 10,
          tempMinCritical: 2,
        },
      },
      {
        id: 'fase_3',
        name: 'Florescimento e enchimento de grãos',
        durationShare: 0.3333,
        weight: 1.5,
        thresholds: {
          tempAvgMinIdeal: 15,
          tempAvgMaxIdeal: 30,
          tempAvgMinCritical: 10,
          tempAvgMaxCritical: 34,
          tempMinIdeal: 10,
          tempMaxCritical: 34,
          tempMinCritical: 2,
          precipMinPerDay: 4.17,
        },
      },
      {
        id: 'fase_4',
        name: 'Maturação',
        durationShare: 0.1667,
        weight: 0.75,
        thresholds: {
          tempAvgMinIdeal: 15,
          tempAvgMinCritical: 10,
          tempMinIdeal: 10,
          tempMinCritical: 2,
          rainyDaysMax: 5,
        },
      },
    ],
    yieldModel: {
      baselineYield: 6.06,
      minYield: 5.5,
      maxYield: 6.61,
      sensitivity: 0.35,
      riskWeights: {
        water_stress: 0.5,
        heat_stress: 0.25,
        cold_stress: 0.15,
        water_excess: 0.1,
      },
    },
  },
  {
    id: 'soja',
    name: 'Soja',
    description: 'Cultura anual sensível a estresse hídrico em florescimento.',
    soil: {
      textures: ['medio', 'argiloso'],
      drainage: ['bom', 'medio'],
      irrigationRecommended: false,
    },
    stages: [
      {
        id: 'estabelecimento',
        name: 'Estabelecimento',
        durationShare: 0.2,
        weight: 0.9,
        thresholds: {
          tempMinIdeal: 20,
          tempMaxIdeal: 30,
          tempMinCritical: 12,
          tempMaxCritical: 35,
          precipMinPerDay: 2.5,
          precipMaxPerDay: 10,
          windMax: 16,
          humidityMin: 45,
          humidityMax: 85,
          pestTempMin: 20,
          pestTempMax: 30,
          pestHumidityMin: 70,
        },
      },
      {
        id: 'vegetativo',
        name: 'Desenvolvimento vegetativo',
        durationShare: 0.35,
        weight: 1,
        thresholds: {
          tempMinIdeal: 20,
          tempMaxIdeal: 32,
          tempMinCritical: 12,
          tempMaxCritical: 35,
          precipMinPerDay: 2.8,
          precipMaxPerDay: 10,
          windMax: 16,
          humidityMin: 45,
          humidityMax: 85,
          pestTempMin: 20,
          pestTempMax: 32,
          pestHumidityMin: 70,
        },
      },
      {
        id: 'florescimento',
        name: 'Florescimento',
        durationShare: 0.25,
        weight: 1.3,
        thresholds: {
          tempMinIdeal: 20,
          tempMaxIdeal: 30,
          tempMinCritical: 14,
          tempMaxCritical: 35,
          precipMinPerDay: 3,
          precipMaxPerDay: 9,
          windMax: 14,
          humidityMin: 50,
          humidityMax: 85,
          pestTempMin: 20,
          pestTempMax: 30,
          pestHumidityMin: 75,
        },
      },
      {
        id: 'enchimento',
        name: 'Enchimento de grãos',
        durationShare: 0.2,
        weight: 1.1,
        thresholds: {
          tempMinIdeal: 18,
          tempMaxIdeal: 30,
          tempMinCritical: 12,
          tempMaxCritical: 34,
          precipMinPerDay: 2.5,
          precipMaxPerDay: 9,
          windMax: 16,
          humidityMin: 45,
          humidityMax: 85,
          pestTempMin: 20,
          pestTempMax: 30,
          pestHumidityMin: 70,
        },
      },
    ],
    yieldModel: {
      baselineYield: 3.2,
      minYield: 1.5,
      maxYield: 5,
      sensitivity: 0.65,
      riskWeights: {
        water_stress: 0.35,
        water_excess: 0.15,
        heat_stress: 0.2,
        cold_stress: 0.08,
        wind_risk: 0.05,
        pest_disease: 0.1,
        soil_suitability: 0.07,
      },
    },
  },
  {
    id: 'cafe',
    name: 'Café',
    description: 'Cultura perene com forte sensibilidade térmica na florada.',
    soil: {
      textures: ['medio', 'argiloso'],
      drainage: ['bom', 'medio'],
      irrigationRecommended: true,
    },
    stages: [
      {
        id: 'floracao',
        name: 'Floração',
        durationShare: 0.3,
        weight: 1.2,
        thresholds: {
          tempMinIdeal: 18,
          tempMaxIdeal: 26,
          tempMinCritical: 10,
          tempMaxCritical: 30,
          precipMinPerDay: 2,
          precipMaxPerDay: 8,
          windMax: 14,
          humidityMin: 50,
          humidityMax: 85,
          pestTempMin: 18,
          pestTempMax: 28,
          pestHumidityMin: 75,
        },
      },
      {
        id: 'frutificacao',
        name: 'Frutificação',
        durationShare: 0.4,
        weight: 1.1,
        thresholds: {
          tempMinIdeal: 18,
          tempMaxIdeal: 28,
          tempMinCritical: 10,
          tempMaxCritical: 32,
          precipMinPerDay: 2,
          precipMaxPerDay: 8,
          windMax: 14,
          humidityMin: 50,
          humidityMax: 85,
          pestTempMin: 18,
          pestTempMax: 28,
          pestHumidityMin: 75,
        },
      },
      {
        id: 'maturacao',
        name: 'Maturação',
        durationShare: 0.3,
        weight: 1,
        thresholds: {
          tempMinIdeal: 18,
          tempMaxIdeal: 28,
          tempMinCritical: 10,
          tempMaxCritical: 32,
          precipMinPerDay: 1.8,
          precipMaxPerDay: 7,
          windMax: 14,
          humidityMin: 50,
          humidityMax: 85,
          pestTempMin: 18,
          pestTempMax: 28,
          pestHumidityMin: 75,
        },
      },
    ],
    yieldModel: {
      baselineYield: 2,
      minYield: 1,
      maxYield: 3.6,
      sensitivity: 0.6,
      riskWeights: {
        water_stress: 0.25,
        water_excess: 0.15,
        heat_stress: 0.2,
        cold_stress: 0.15,
        wind_risk: 0.05,
        pest_disease: 0.1,
        soil_suitability: 0.1,
      },
    },
  },
];
